name: Deploy to Google Cloud

on:
    #  push:
    #     branches:
    #       - main
     workflow_dispatch:

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build zip file
      run: |
        cd src
        zip -r ../function_code.zip .
        cd ..

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy with Terraform
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
