name: Destroy Google Cloud

on:
    #  push:
    #     branches:
    #       - main
     workflow_dispatch:

jobs:
 deploy:
    runs-on: ubuntu-latest
    environment: GCP_PROJECT_ID
    steps:
    - uses: actions/checkout@v3.0.0

    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"
        create_credentials_file: true
        export_environment_variables: true

    - name: Destroy with Terraform
      run: |
        cd infra
        terraform init
        terraform plan -destroy
        terraform destroy -auto-approve
